FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# user-service

User Service is an API for user management.

## User collection [/users]

### List All Users within the organization [GET]

+ Response 200 (application/json)

        {
            "count": 1,
            "next": null,
            "previous": null,
            "results": [
                {
                    "id": 2,
                    "username": "jkowalski",
                    "first_name": "Jan",
                    "last_name": "Kowalski",
                    "access_key": "3ca66ad205294df6a11863fb9ad68da2",
                    "organization": {
                        "id": 2,
                        "name": "My Organization",
                        "slug_name": "my-organization"
                    },
                    "is_organization_admin": true
                }
            ]
        }
